"""create document_snapshots table

Revision ID: 5c65f88b2cd4
Revises: 
Create Date: 2026-07-18 23:46:12.408682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c65f88b2cd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content_state', sa.LargeBinary(), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_snapshots_document_id'), 'document_snapshots', ['document_id'], unique=True)
    op.create_index(op.f('ix_document_snapshots_id'), 'document_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_snapshots_id'), table_name='document_snapshots')
    op.drop_index(op.f('ix_document_snapshots_document_id'), table_name='document_snapshots')
    op.drop_table('document_snapshots')
    # ### end Alembic commands ###
